# Build C:\LittleCode-test\.env.local from production .env.local with staging overrides.
$ErrorActionPreference = "Stop"

$prodEnv = "C:\LittleCode\.env.local"
$testEnv = "C:\LittleCode-test\.env.local"
$stripeTestEnv = "C:\LittleCode-test\.env.stripe-test.local"

if (-not (Test-Path $prodEnv)) {
  throw "Missing $prodEnv"
}

$lines = Get-Content $prodEnv
$out = New-Object System.Collections.Generic.List[string]

function Get-ExistingStagingGatePassword {
  param([string]$Path)
  if (-not (Test-Path $Path)) {
    return $null
  }
  foreach ($line in Get-Content $Path) {
    $trimmed = $line.Trim()
    if ($trimmed -match '^STAGING_GATE_PASSWORD=(.+)$') {
      $value = $Matches[1].Trim()
      if ($value) {
        return $value
      }
    }
  }
  return $null
}

function New-RandomStagingGatePassword {
  param([int]$Length = 16)
  $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  -join ((1..$Length) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
}

$existingGatePassword = Get-ExistingStagingGatePassword -Path $testEnv
$stagingGatePassword = if ($existingGatePassword) { $existingGatePassword } else { New-RandomStagingGatePassword }

$out.Add("# Staging - test.quizzora.org (generated by scripts/write-test-env.ps1)")
$out.Add("APP_ENV=staging")
$out.Add("APP_STAGING_LABEL=Quizzora test (test.quizzora.org)")
$out.Add("APP_BASE_URL=https://test.quizzora.org")
$out.Add("SQLITE_DATABASE_PATH=C:\LittleCode-test\data\littlecode.sqlite")
$out.Add("AUTH_COOKIE_SECURE=true")
$out.Add("")
$out.Add("# Faster AI quiz generation on staging (diagrams add significant OpenAI latency).")
$out.Add("OPENAI_IMAGE_GENERATION=false")
$out.Add("")
$out.Add("# Shared tester gate (see docs/TEST-ENVIRONMENT.md). Not used on production.")
$out.Add("STAGING_GATE_USER=tester")
$out.Add("STAGING_GATE_PASSWORD=$stagingGatePassword")
$out.Add("")

$skipKeys = @{
  "APP_ENV" = $true
  "APP_STAGING_LABEL" = $true
  "APP_BASE_URL" = $true
  "SQLITE_DATABASE_PATH" = $true
  "AUTH_COOKIE_SECURE" = $true
  "STAGING_GATE_USER" = $true
  "STAGING_GATE_PASSWORD" = $true
  "STRIPE_SECRET_KEY" = $true
  "STRIPE_WEBHOOK_SECRET" = $true
  "STRIPE_PRICE_MONTHLY" = $true
  "STRIPE_PRICE_YEARLY" = $true
  "STRIPE_PRICE_FAMILY_MONTHLY" = $true
  "STRIPE_PRICE_FAMILY_YEARLY" = $true
}

foreach ($line in $lines) {
  $trimmed = $line.Trim()
  if (-not $trimmed -or $trimmed.StartsWith("#")) {
    continue
  }
  $sep = $trimmed.IndexOf("=")
  if ($sep -lt 1) {
    continue
  }
  $key = $trimmed.Substring(0, $sep).Trim()
  if ($skipKeys.ContainsKey($key)) {
    continue
  }
  $out.Add($trimmed)
}

$out.Add("")
$out.Add("# Stripe TEST mode - run: npm run stripe:sandbox (with STRIPE_TEST_SECRET_KEY)")
if (Test-Path $stripeTestEnv) {
  foreach ($line in Get-Content $stripeTestEnv) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }
    if ($trimmed -match '^(STRIPE_|BILLING_DISPLAY_)') {
      $out.Add($trimmed)
    }
  }
} else {
  $out.Add("# STRIPE_SECRET_KEY=sk_test_...")
  $out.Add("# STRIPE_WEBHOOK_SECRET=whsec_...")
  $out.Add("# STRIPE_PRICE_MONTHLY=price_...")
  $out.Add("# STRIPE_PRICE_YEARLY=price_...")
  $out.Add("# STRIPE_PRICE_FAMILY_MONTHLY=price_...")
  $out.Add("# STRIPE_PRICE_FAMILY_YEARLY=price_...")
}

Set-Content -Path $testEnv -Value ($out -join "`r`n") -Encoding UTF8
Write-Host "Wrote $testEnv"
